baseURL = "https://26hz.com.cn"
languageCode = "en-us"
title = "Hertz赫兹空间"
theme = "zev"
paginate = 7
copyright = "© 2023 <a href=\"https://git.26hz.com.cn/hertz\">Hertz Hwang</a>."
hasCJKLanguage = true

# 作者信息
[author]
  name = "Hertz Hwang"
  email = "hertz@26hz.com.cn"
  description = "喵~~"
  #avatar = "https://chowray.netlify.app/images/author/avatar.gif"
  avatar = "https://file.26hz.com.cn/img/avatar.jpg"

# 菜单/导航栏
[menu]
  # 顶部导航栏
  [[menu.main]]
    identifier = "/"
    name = "主页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "/posts"
    name = "文章"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "/categories"
    name = "分类"
    url = "/categories"
    weight = 3
  [[menu.main]]
    identifier = "/link"
    name = "链接"
    url = "/link"
    weight = 4
  [[menu.main]]
    identifier = "/about"
    name = "关于"
    url = "/about"
    weight = 5
  
  # 底部社交图标
  [[menu.social]]
    identifier = "bilibili"
    name = "bilibili"
    url = "https://space.bilibili.com/2508980"
    weight = 1
  [[menu.social]]
    identifier = "github"
    name = "git"
    url = "https://git.26hz.com.cn/hertz"
    weight = 2
  [[menu.social]]
    identifier = "weibo"
    name = "weibo"
    url = "https://weibo.com/u/2461957043"
    weight = 3

# URL格式
[permalinks]
  posts = "/:section/:year:month:day:15:04/"
  files = "/:section/:year:month:day:15:04/"
  docs = "/:section/:year:month:day:15:04/"

# 主题相关配置项
[params]
  keywords = ['theme', 'zev']
  description = ""
  mainSections = ["posts"]
  # 国内备案号
  beian = "闽ICP备2023012558号-1"
  gonganbeian = "闽公网安备 35012102500827号"
  # TOC目录出现字符长度限制
  toc_show_len = 300

  [params.analytics]
    baidu = ""

  [params.widget]
    # 相关文章推荐数量
    articles_count = 6
    # 分类相关显示数量
    categories_count = 6
    # 标签相关显示数量
    tags_count = 12

  [params.aplayer]
    theme = "#b7daff"
    autoplay = false
    loop = "none"
    mutex = true

  [params.dplayer]
    theme = "#b7daff"
    autoplay = false
    loop = false
    mutex = true
